### ISSUE TITLE
[Bug]: Colour of Email and Password label changing

### ISSUE THREAD

**Issue by GosuCode** [piyushgarg-dev/review-app#80] opened 2023-10-08 10:54 UTC
### Describe the bug

Email and Password labels colour changing while entering the wrong credentials or not giving credentials.

### To Reproduce

1. Go to 'login page'
2. Click on 'login without entering any credentials or enter wrong information'
3. See error

### Expected behavior

The Email and Password label should not be red when error occurs.

### Screenshots/Videos

![beforeerror](https://github.com/piyushgarg-dev/review-app/assets/104659592/ef6f3319-964f-4f00-b01d-8bb63c2e7ef2)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by anshul-kh** [comment] 2023-10-08 11:38
Hi @GosuCode ! Please Assign this issue to me . I would like to work on this issue.

**Comment by GosuCode** [comment] 2023-10-08 11:46
> Hi @GosuCode ! Please Assign this issue to me . I would like to work on this issue.
> 

I have already submitted the PR for this bug.

**Comment by piyushgarg-dev** [comment] 2023-10-08 13:10
This was done intentionally, This is not a bug.
Thanks for contributing 😄

**Closed by piyushgarg-dev** 2023-10-08 13:10 UTC
Labels: bug
